# Generated by Django 4.1.2 on 2022-10-27 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(default='admin', max_length=255)),
                ('date_joined', models.DateField(default=datetime.date(2015, 1, 13))),
            ],
        ),
    ]
