# Generated by Django 4.1.2 on 2022-10-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='https://pbs.twimg.com/media/BcINeMVCIAABeWd.jpg', max_length=255),
        ),
    ]
