# Generated by Django 4.1.2 on 2022-10-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_name_csv',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_name_xml',
            field=models.FileField(upload_to=''),
        ),
    ]
