# Generated by Django 4.1.2 on 2022-10-31 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_file_file_name_csv_alter_file_file_name_xml'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_name_csv',
            field=models.FileField(upload_to='files/file_csv'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_name_xml',
            field=models.FileField(upload_to='files/file_xml'),
        ),
    ]
